package colruyt.employee360.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import colruyt.employee360.entity.Employee;
import colruyt.employee360.repository.EmployeeRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/employee360/employee") // This means URL's start with /demo (after Application path)
@CrossOrigin("*")
public class EmployeeController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeRepository employeeRepository;
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Employee emp = new Employee();
		emp.setEMP_NAME(name);
		employeeRepository.save(emp);
		return "Saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Employee> getAllEmployees() {
		// This returns a JSON or XML with the users
		System.out.println("Trying to get all employees");
		return employeeRepository.findAll();
	}
}
