package colruyt.employee360.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import colruyt.employee360.entity.EmployeeSkills;
import colruyt.employee360.repository.EmployeeSkillsRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/employee360/skills") // This means URL's start with /demo (after Application path)
@CrossOrigin("*")
public class EmployeeSkillsController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeSkillsRepository employeeSkillRepository;
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String skill) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		EmployeeSkills empSkills = new EmployeeSkills();
		empSkills.setSkill(skill);
		employeeSkillRepository.save(empSkills);
		return "Saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<EmployeeSkills> getAllEmployeeSkills() {
		// This returns a JSON or XML with the users
		System.out.println("Trying to get all skills");
		return employeeSkillRepository.findAll();
	}
}
